name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *' # run at 01:30 UTC

jobs:
  build:
    name: Test DOPA
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        config: [release] # [debug,release]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          7.0.x
          8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c ${{ matrix.config }} --no-restore
    - name: Test
      run: dotnet test -c ${{ matrix.config }} --no-build --verbosity normal

  publish:
    name: Publish DOPA
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          7.0.x
          8.0.x
    - name: Publish on version change
      uses: alirezanet/publish-nuget@v3.0.4
      with:
        PROJECT_FILE_PATH: src/DOPA/DOPA.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        INCLUDE_SYMBOLS: true
